### ISSUE TITLE
Reply Recursion

### ISSUE THREAD

**Issue by Neshura87** [TeamPiped/lemmy-piped-link-bot#10]
See: https://bookwormstory.social/comment/716520

You should probably fix that ASAP or instances will start blocking the bot for spam

**Comment by Asudox** [comment]
I guess it can be changed with a simple ID check to see if the comment its replying is from its own or not. Might open a PR for this if I have the time today.

**Comment by Asudox** [comment]
> > I guess it can be fixed with a simple ID check to see if the comment its replying to is its own or not.
> 
> It shouldn't be posting a YouTube link at all in the first place.
> 
> 

Oh yeah, my bad.
