### ISSUE TITLE
Request: Remove ?si= from links 

### ISSUE THREAD

**Issue by beckerist** [TeamPiped/lemmy-piped-link-bot#223]
YouTube recently added a new tracking method to shared links by adding si={blob}

This tracks who shared it and with whom, when, where it was shared to, etc... It's only a request as it's not a bug but any effort to remove Google's tracking would be appreciated.

**Comment by random-integer** [comment]
I came to this project's issues page just to post about removing `?si=`, but I guess I never have any original thought, lol.

**Comment by FireMasterK** [comment]
The links now will no longer the si parameter. We were always safe from that tracking since Piped doesn't recognize that parameter to begin with.
