### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by iwannet** [TeamPiped/lemmy-piped-link-bot#4]
It doesnt detect timestamps.
Here is an example: https://lemmy.ml/comment/2094090

Thanks for the bot !

**Comment by FireMasterK** [comment]
The original link doesn't seem to be a working timestamp link 🤔
It should work fine with timestamps

**Comment by iwannet** [comment]
The timestamp works find in newpipe though

**Comment by iwannet** [comment]
The timestamp works find in newpipe though. Maybe its a newpipe related issue, cuz i exported the link from newpipe.

**Comment by FireMasterK** [comment]
The problem appears to be that the link you've shared to lemmy is `https://www.youtube.com/watch?v=UJeSWbR6W04&amp;t=456`. It should have been `https://www.youtube.com/watch?v=UJeSWbR6W04&t=456`.

I think the Lemmy client you used had some issues with encoding the URL.

**Comment by iwannet** [comment]
Okay thanks !

Btw: thanks for piped, i use it every day, its so amazing.
