### ISSUE TITLE
Feature Request: Work on all of Fediverse and not just lemmy

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [TeamPiped/lemmy-piped-link-bot#49]
I think the title says it all, be great if anyone who posts on mastodon, friendica, etc. a stupid YT links gets a better one

**Comment by FireMasterK** [comment]
Hi, you can check out https://github.com/TeamPiped/mastodon-piped-link-bot now!

**Comment by DetroitLibertyPenguin** [comment]
that's awesome. Do you have it running live on any particular instance I
could see it?
Jim Fulner
22100 Armada Ridge Rd.,
Armada, MI 48005-3204
(P) 248-971-0259
(M) 248-765-7458
(H) 586-473-7007

Telephony eliminates confusion
