### ISSUE TITLE
[Bug] Bot detected and acted on non-video link

### ISSUE THREAD

**Issue by tn5421** [TeamPiped/lemmy-piped-link-bot#77]
Realistically, the bot should not have replied to this post at all.

Permalink of parent comment: https://lemmy.dbzer0.com/comment/4242572

Permalink of comment: https://lemmy.dbzer0.com/comment/4248592

![image](https://github.com/TeamPiped/lemmy-piped-link-bot/assets/2477053/508eb239-41d3-47b2-adb7-c563bbe8a7a1)

**Comment by FireMasterK** [comment]
Hey, you missed the YouTube link here:
![image](https://github.com/TeamPiped/lemmy-piped-link-bot/assets/20838718/19e7d715-a01b-4c25-9381-8aa9ca482304)

Hope this helps! :)
